const WORKER_FIELDS = [
  'worker_id',
  'first_name',
  'last_name',
  'nickname',
  'nationality',
  'native_language',
  'phone',
  'whatsapp',
  'telegram',
  'line',
  'passport_number',
  'visa_type',
  'visa_expiration',
  'profession',
  'skills',
  'years_experience',
  'current_employer',
  'previous_employers',
  'current_city',
  'availability',
  'status',
  'notes',
  'documents',
  'tags',
  'created_at',
  'updated_at',
  'archived_at',
];

const WORKER_DEFAULTS = {
  last_name: '',
  nickname: '',
  nationality: '',
  native_language: '',
  phone: '',
  whatsapp: '',
  telegram: '',
  line: '',
  passport_number: '',
  visa_type: 'unknown',
  visa_expiration: '',
  profession: '',
  skills: '',
  years_experience: '',
  current_employer: '',
  previous_employers: '',
  current_city: '',
  availability: 'unknown',
  status: 'new',
  notes: '',
  documents: '',
  tags: '',
  archived_at: '',
};

const WORKER_ENUMS = {
  visa_type: ['unknown', 'tourist', 'work', 'student', 'resident', 'refugee', 'none', 'other'],
  availability: ['unknown', 'immediate', 'this_week', 'this_month', 'unavailable'],
  status: ['new', 'screening', 'ready', 'working', 'inactive', 'not_eligible', 'archived'],
};

module.exports = {
  WORKER_DEFAULTS,
  WORKER_ENUMS,
  WORKER_FIELDS,
};
