const SAMPLE_JOBS = [
  {
    jobId: 'job_sample_construction_tel_aviv',
    title: 'Construction worker',
    workSector: 'Construction',
    profession: 'Construction worker',
    city: 'Tel Aviv',
    area: 'Gush Dan',
    employerName: 'Aviv Construction',
    salaryText: '700 NIS per day',
    description: 'Construction work in Tel Aviv.',
    contactMethod: 'Phone',
    contactValue: '',
    status: 'Active',
    createdAt: '2026-07-13T00:00:00.000Z',
    updatedAt: '2026-07-13T00:00:00.000Z',
  },
  {
    jobId: 'job_sample_agriculture_ashkelon',
    title: 'Agriculture worker',
    workSector: 'Agriculture',
    profession: 'Agriculture worker',
    city: 'Ashkelon',
    area: 'South',
    employerName: 'Green Fields',
    salaryText: '45 NIS per hour',
    description: 'Agriculture work near Ashkelon.',
    contactMethod: 'Phone',
    contactValue: '',
    status: 'Active',
    createdAt: '2026-07-13T00:00:00.000Z',
    updatedAt: '2026-07-13T00:00:00.000Z',
  },
  {
    jobId: 'job_sample_caregiver_jerusalem',
    title: 'Caregiver',
    workSector: 'Caregiving',
    profession: 'Caregiver',
    city: 'Jerusalem',
    area: 'Jerusalem',
    employerName: 'Golden Care',
    salaryText: 'Monthly salary',
    description: 'Caregiving work in Jerusalem.',
    contactMethod: 'Phone',
    contactValue: '',
    status: 'Active',
    createdAt: '2026-07-13T00:00:00.000Z',
    updatedAt: '2026-07-13T00:00:00.000Z',
  },
];

module.exports = {
  SAMPLE_JOBS,
};
