const CONTACT_FIELDS = [
  'contact_id',
  'first_name',
  'last_name',
  'display_name',
  'email',
  'phone',
  'whatsapp_id',
  'telegram_id',
  'telegram_username',
  'line_id',
  'preferred_channel',
  'country',
  'city',
  'language',
  'status',
  'source',
  'source_detail',
  'interest',
  'priority',
  'assigned_to',
  'next_follow_up_at',
  'last_contacted_at',
  'tags',
  'ai_summary',
  'ai_next_action',
  'ai_opt_in',
  'marketing_opt_in',
  'data_consent',
  'notes_count',
  'history_count',
  'created_at',
  'updated_at',
  'archived_at',
];

const CONTACT_DEFAULTS = {
  last_name: '',
  display_name: '',
  email: '',
  phone: '',
  whatsapp_id: '',
  telegram_id: '',
  telegram_username: '',
  line_id: '',
  preferred_channel: 'unknown',
  country: '',
  city: '',
  language: 'unknown',
  status: 'new',
  source: 'manual',
  source_detail: '',
  interest: 'unknown',
  priority: 'normal',
  assigned_to: '',
  next_follow_up_at: '',
  last_contacted_at: '',
  tags: '',
  ai_summary: '',
  ai_next_action: '',
  ai_opt_in: false,
  marketing_opt_in: false,
  data_consent: false,
  notes_count: 0,
  history_count: 0,
  archived_at: '',
};

const CONTACT_ENUMS = {
  preferred_channel: ['unknown', 'phone', 'email', 'whatsapp', 'telegram', 'line', 'in_person'],
  language: ['unknown', 'english', 'hebrew', 'spanish', 'russian', 'french', 'arabic', 'other'],
  status: [
    'new',
    'reviewed',
    'contacted',
    'engaged',
    'follow_up',
    'active_member',
    'inactive',
    'not_relevant',
    'archived',
  ],
  source: [
    'manual',
    'website',
    'whatsapp',
    'telegram',
    'line',
    'referral',
    'event',
    'facebook',
    'instagram',
    'google',
    'partner',
    'import',
    'ai_agent',
    'other',
  ],
  interest: ['unknown', 'community', 'events', 'housing', 'jobs', 'business', 'language', 'support', 'other'],
  priority: ['low', 'normal', 'high', 'urgent'],
};

module.exports = {
  CONTACT_DEFAULTS,
  CONTACT_ENUMS,
  CONTACT_FIELDS,
};
